default: &default
    adapter: postgresql
    encoding: unicode
    database: ft_development
    host: localhost
    pool: 5
    username: postgres
    password: postgres

development:
  <<: *default
  database: delivery_traker_development

test:
  <<: *default
  database: delivery_traker_test

production:
  <<: *default
  database: delivery_traker_production